
version: 2

models:
  - name: stg_superheroes
    description: Demographics about each superhero such as name.
    columns:
      - name: name
        tests:
          - not_null

      - name: weight
        tests:
          - positive_values
